spring:
  application:
    name: law_system
  main:
    allow-circular-references: true
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/law_system
      username: root
      password: 123456

server:
  port: 8080
#mybatis:
#  #mapper配置文件
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.ylsf.grk.law_system.pojo.entity
#  configuration:
#    #开启驼峰命名
#    map-underscore-to-camel-case: true
mybatis-plus:
  # 搜索指定包别名
  type-aliases-package: com.ylsf.grk.law_system.pojo.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/*.xml
  # 全局配置
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新mapper 调试神器
    refresh-mapper: true
    # 配置
    configuration:
      # 驼峰式命名
      map-underscore-to-camel-case: true
      # 全局映射器启用缓存
      cache-enabled: true
      # 指定 MyBatis 所用日志的具体实现
      log-impl: org.slf4j;
      # 配置默认的执行器
      default-executor-type: reuse
      # 允许 JDBC 支持自动生成主键
      use-generated-keys: true

law:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    employee-secret-key: cereshuzhitingnizhenbangcereshuzhitingnizhenbang
    # 设置jwt过期时间
    employee-ttl: 7200000
    # 设置前端传递过来的令牌名称
    employee-token-name: token

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#控制台输出debug语句
logging:
  level:
    com.ylsf.grk.law_system: debug


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    urls-primary-name: 律师事务所系统
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ylsf.grk.law_system.controller

# knife4j的增强配置，不需要增强可以不配（建议配置一下）
knife4j:
  enable: true
  setting:
    language: zh_cn

langchain4j:
  open-ai:
    chat-model:
      api-key: sk-c2921745c40944ae8d89c55906aadcfe
      model-name: deepseek-reasoner
      base-url: https://api.deepseek.com

